//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torn5 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class MainForm {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal MainForm() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Torn5.MainForm", typeof(MainForm).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap buttonAddColumn_Image {
			get {
				object obj = ResourceManager.GetObject("buttonAddColumn.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonAddRow_Image {
			get {
				object obj = ResourceManager.GetObject("buttonAddRow.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonClose_Image {
			get {
				object obj = ResourceManager.GetObject("buttonClose.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonCommit_Image {
			get {
				object obj = ResourceManager.GetObject("buttonCommit.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonConfigureReports_Image {
			get {
				object obj = ResourceManager.GetObject("buttonConfigureReports.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonEdit_Image {
			get {
				object obj = ResourceManager.GetObject("buttonEdit.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonExportReports_Image {
			get {
				object obj = ResourceManager.GetObject("buttonExportReports.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonLatestGame_Image {
			get {
				object obj = ResourceManager.GetObject("buttonLatestGame.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonNew_Image {
			get {
				object obj = ResourceManager.GetObject("buttonNew.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonOpen_Image {
			get {
				object obj = ResourceManager.GetObject("buttonOpen.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonRemoveColumn_Image {
			get {
				object obj = ResourceManager.GetObject("buttonRemoveColumn.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonRemoveRow_Image {
			get {
				object obj = ResourceManager.GetObject("buttonRemoveRow.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonSetFolder_Image {
			get {
				object obj = ResourceManager.GetObject("buttonSetFolder.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonUploadReports_Image {
			get {
				object obj = ResourceManager.GetObject("buttonUploadReports.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Windows.Forms.ImageListStreamer imageListLeagues_ImageStream {
			get {
				object obj = ResourceManager.GetObject("imageListLeagues.ImageStream", resourceCulture);
				return ((System.Windows.Forms.ImageListStreamer)(obj));
			}
		}
		
		internal static System.Windows.Forms.ImageListStreamer imageListPacks_ImageStream {
			get {
				object obj = ResourceManager.GetObject("imageListPacks.ImageStream", resourceCulture);
				return ((System.Windows.Forms.ImageListStreamer)(obj));
			}
		}
	}
}
